### ISSUE TITLE
[Feature Request] Add new feauture from my repo :D

### ISSUE THREAD

**Issue by YT-Advanced** [sn-o-w/WSA-Magisk#2]
### Is your feature request related to a problem?

Nope

### Describe the solution you'd like

Here is my new feature:
- Support to install WSA in Windows 10 (Version 10.0.19041.264 or higher)
- `Remove-amazon` support in Custom Build
- Support `Magisk-Delta` Custom Build
- Support build `x64 & arm64 Both` in Custom Build
- Add `Check Update` for Auto Build

### Additional context

My repos: https://github.com/YT-Advanced/WSA-Script

**Comment by sn-o-w** [comment]
I don't use Win 10, so I'll say no to this.
