### ISSUE TITLE
More user-friendly releases

### ISSUE THREAD

**Issue by CarlGao4** [sn-o-w/WSA-Magisk#3]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I've tested on my local machine but I don't know how to make it on GitHub Actions. Can you contact me at gaoweiqicarl1@163.com for further discussion?

**Comment by YT-Advanced** [comment]
@CarlGao4 What are you mentioning ? How to create your own Custom Build using Github Action or How to create a workflow that can automatically build?

**Comment by CarlGao4** [comment]
A zip format file must be extracted before running. I've successfully compressed the outputs into virtual hard disk (.vhdx), so it can be directly executed without occupying extra 4GB disk space.

**Comment by YT-Advanced** [comment]
> To achieve this on gh Action, the action should be continued on a Windows environment. I don't know how to pass files to later steps.

You can use cache to archive the file. [Follow this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Comment by YT-Advanced** [comment]
> A zip format file must be extracted before running. I've successfully compressed the outputs into virtual hard disk (.vhdx), so it can be directly executed without occupying extra 4GB disk space. I think that this may be a better solution than releasing zip files.

Hmm, you mean archive WSA .zip file then it can be used for the next workflow ?

**Comment by CarlGao4** [comment]
Yes

**Comment by YT-Advanced** [comment]
> Hmm, you mean archive WSA .zip file then it can be used for the next workflow ?

Good idea but all of them need to download again when use :)))) And as I remembered, there are some limitation for cache file

**Comment by CarlGao4** [comment]
> all of them need to download again when use

What do you mean? 
By the way, can you send emails?

**Comment by YT-Advanced** [comment]
> What do you mean?

If you using cache, the workflow must be downloaded the file from cache to use it.

**Comment by CarlGao4** [comment]
Sorry, but I still can't understand - could you please use more formal grammar?

**Comment by YT-Advanced** [comment]
> Sorry, but I still can't understand - could you please use more formal grammar? 

Hmm. When you use cache, the file will be stored on Github Server. So if you run workflow, it need to download the cache file for running. All of these method have a same time and the same job

**Comment by CarlGao4** [comment]
Thanks, I'll try to find a solution

**Comment by CarlGao4** [comment]
Oh, I've found this: https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs

**Comment by CarlGao4** [comment]
Finally ...
I've finished it. [CarlGao4/WSA-Magisk-test](https://github.com/CarlGao4/WSA-Magisk-test)

**Comment by CarlGao4** [comment]
Finally ...
I've finished it. [CarlGao4/WSA-Magisk-test](https://github.com/CarlGao4/WSA-Magisk-test)
